### ISSUE TITLE
Start bot-procman, bot-lcm-tunnel on system boot

### ISSUE THREAD

**Issue by wxmerkt** [openhumanoids/valkyrie-lcm-distro#2]

**Comment by mauricefallon** [comment]
Please describe

**Comment by wxmerkt** [comment]
Scripts that automatically start `bot-lcm-tunnel` and `bot-procman-deputy -n link` on system boot so that we can bot-procman-sheriff to start/stop our controllers.

These are already working and tested on my machine, cf. https://github.com/openhumanoids/valkyrie-lcm-distro/pull/3

The advantage is that after the robot is booted, the LCM tunnel is already created and a procman-deputy running. Through this we can start/stop controllers via runval instead of SSH-ing in https://github.com/openhumanoids/oh-distro-private/pull/2307/files#diff-eb2c268f23a8a3b3d6f823dbc64fff39R99

**Comment by mauricefallon** [comment]
A tunnel shouldn't be necessary in the long run
