### ISSUE TITLE
Investigate LCM UDP transmission from robot

### ISSUE THREAD

**Issue by wxmerkt** [openhumanoids/valkyrie-lcm-distro#5]
... to avoid having to use the LCM tunnel if possible

**Comment by wxmerkt** [comment]
@mauricefallon I debugged the communication coming from the robot. **We can do UDP without the tunnel**. The communities were not set up properly. Best to have a quick chat and sketch on how to separate communities to not spam link with data we don't need to broadcast there.

**Comment by patmarion** [comment]
let me know if you want to talk about lcm communities.  Are you familiar with the community bridge tool and mapping (in the .cfg file) that we used for atlas onboard computers?  I think we worked out a system that worked pretty well for us.

**Comment by wxmerkt** [comment]
I'll have a look into the community bridge tool - I've seen it in the config files but hadn't used it so far. Will have a chat with Maurice and happy to set up a call to discuss ideas/needs and get your input :).

I've just invited you to a [GoogleDoc](https://docs.google.com/drawings/d/1PMUnv_Fn5fvv7Pb0_kK_BLBWG-_En1vHpLMMKYhgfek/edit?usp=sharing) with a first proposal/outline of communities - I've taken what's there for Atlas and transferred it to how we could reuse/adapt it by adding similar sections in the same configuration file. 

Needs more work regarding setup of the observer workstation and wiring of the second subnet. Looking forward to hearing your thoughts/expertise/input on this :)

**Comment by patmarion** [comment]
A useful view of the communities is to open an instance of bot-spy within each community on each host, and take a screenshot, in order to list the full set of lcm channels and message frequency and bandwidth under typical operation.  It might not be an interesting picture until you have communities running, but I could do it for our Atlas setup.

**Comment by wxmerkt** [comment]
Didn't take a screenshot of the bandwidth yet but link didn't publish anything to procman for about 22s at a time very regularly and zelda dropped out for 9s when the multisense-driver was running (and the multisense driver was on vis which is suboptimal because it drops images left and right)

**Comment by patmarion** [comment]
This sounds like maybe an mtu problem?

**Comment by wxmerkt** [comment]
Yeah, never set the MTU for the Netgear switch above 1500 so very likely. Onboard (and that includes Zelda), it uses 9000 (I believe to remember from a conversation - will verify)

**Comment by wxmerkt** [comment]
Definitely need to separate communities. We can manage to get the control rate to be 0Hz or 120Hz by flooding it...

**Comment by VladimirIvan** [comment]
The university network (switch) is set to block the traffic for 10s when it detects suspicious behaviour (e.g. DoS attack). If the Multisense packets somehow make it all the way past the router, it would cause a 10s ban on all traffic on the router's internet port. That could be something to look for or use as a indicator when debugging this.

**Comment by wxmerkt** [comment]
We should have a chat about this - operation has shown that we need to either figure out 

a) being able to broadcast UDP from vis with ttl=1
b) set up communities/tunnels similar to Atlas

Is [that proposal](https://docs.google.com/drawings/d/1PMUnv_Fn5fvv7Pb0_kK_BLBWG-_En1vHpLMMKYhgfek/edit) ok? Any input and feedback?

**Comment by wxmerkt** [comment]
I've been running more experiments and the issue appears to be the MTU which is set at 1500. Slowly increasing the message size beyond 1500 bytes will result in a gradual decline in controller frequency with only one controller running.

| Message Size Publisher A | Message Size Publisher B | Control Rate Behaviour |
| --- | --- | --- |
| 1901 bytes (full robot) | - | Drop |
| 1462 bytes (30 joints) | - | OK |
| 1492 bytes (32 joints) | - | OK |
| 1505 bytes (34 joints) | - | Drop to 496 Hz |
| 1517 bytes (35 joints) | - | Drop to 496 Hz |
| 1550 bytes (36 joints) | - | Drop to 488 Hz |
| 1594 bytes (38 joints) | - | Drop to 480 Hz |
| 1004 bytes (0 joints) | 1004 bytes (0 joints) | Drop |
| 1901 bytes (full robot), via tunnel |  | OK |

Using ttl=0 and bot-lcm-tunnels between link and vis, and zelda and vis, is able to cope with any number of controllers without a drop in rates (tested with IHMC, JointStatePublisher, Neck, Hand, Forearm all running simultaneously). Hence, I'd recommend 
- [ ] setting up bot-lcm-tunnel as a service that auto starts on link and zelda
- [ ] adding bot-lcm-tunnel to robot.pmd or using the network parameter config as with atlas

**Comment by wxmerkt** [comment]
After further discussions, we'd like to implement the following (@patmarion - does this make sense?)
![2016 04 14 valkyrie lcm communities 1](https://cloud.githubusercontent.com/assets/1664508/14533799/8b78b9b8-025e-11e6-9733-73fc5eadba19.png)

**Comment by patmarion** [comment]
Seem reasonable.  I'm having trouble guessing where the issue might be, sounds like it could be a unique interaction between lcm and the real time OS, but I don't know.  We usually set MTU to be higher, like 7200.  Could be that performance drops when large udp packets are fragmented by the OS before multicast.

**Comment by mauricefallon** [comment]
I think its the publish and not the encode step that's the problem.

**Comment by wxmerkt** [comment]
Investigated and decided to use tunnels for now as publishing messages larger than 1500bytes causes control rates to drop. Closing
